version: '3'
services:
  mirrors:
    container_name: mirrors
    network_mode: bridge
    image: seandou/nginx-pubfiles:latest
    restart: always
    ports:
      - "172.17.0.1:1111:80"
    volumes:
      - /data/mirrors:/data/pubfiles
